name = "PairCorrelation"
uuid = "0d5ad3cd-ffd9-4240-b7f9-d441ea4affdd"
authors = ["Josua Grawitter <josua.grawitter@physik.tu-berlin.de>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.7"
FFTW = "1.4"
SpecialFunctions = "2.1"
StaticArrays = "1.3"
